version: '3.3'
services:
    docker:
        container_name: jenkins-docker
        privileged: true
        networks: 
         - jenkins
        environment:
            - DOCKER_TLS_CERTDIR=/certs
        volumes:
            - 'docker-certs-jk:/certs/client'
            - 'jenkins_home:/var/jenkins_home'
        ports:
            - '2376:2376'
            - '3000:3000'
            - '5000:5000'
        image: 'docker:dind'
    myjenkins-blueocean:
        container_name: jenkins-blueocean
        networks: 
            - jenkins
        environment:
            - 'DOCKER_HOST=tcp://docker:2376'
            - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_VERIFY=1
            - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
        ports:
            - '8080:8080'
            - '50000:50000'
        volumes:
            - 'jenkins_home:/var/jenkins_home'
            - 'docker-certs-jk:/certs/client:ro'
            - '$HOME:/home'
        restart: on-failure
        build: 
            context: .
            dockerfile: jenkindockerfile 
volumes:
    jenkins-data:
    jenkins-docker-certs:
    jenkins_home:
    docker-certs-jk:
networks:
    jenkins: